// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1n9BxlvCkKNjyjhSzEu4R8EriARC1lrY',
    appId: '1:246168027355:web:d3ba143b4bb7af5adc4cfe',
    messagingSenderId: '246168027355',
    projectId: 'tumkur-paatashala',
    authDomain: 'tumkur-paatashala.firebaseapp.com',
    storageBucket: 'tumkur-paatashala.appspot.com',
    measurementId: 'G-1E1QX0R4E2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_QNI5vzTwWE-U9G_JLchrZdXsMoKs4TA',
    appId: '1:246168027355:android:ec683d082d0283c5dc4cfe',
    messagingSenderId: '246168027355',
    projectId: 'tumkur-paatashala',
    storageBucket: 'tumkur-paatashala.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7XVW48dAFWuAVkj9K-OzNDyf_eZU1Jck',
    appId: '1:246168027355:ios:df27bc6a0653a640dc4cfe',
    messagingSenderId: '246168027355',
    projectId: 'tumkur-paatashala',
    storageBucket: 'tumkur-paatashala.appspot.com',
    iosClientId: '246168027355-hld6eqe068jaacq0qh31vm7th2qkclpe.apps.googleusercontent.com',
    iosBundleId: 'com.example.tumkurPaatashala',
  );
}
